Exception in thread "main" java.lang.NullPointerException
	at org.apache.hadoop.net.NetUtils.createSocketAddr(NetUtils.java:134)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:156)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:160)
	at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.initialize(SecondaryNameNode.java:131)
	at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.<init>(SecondaryNameNode.java:115)
	at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.main(SecondaryNameNode.java:469)
